# Generated by Django 4.0.4 on 2022-06-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmodel',
            name='image',
        ),
    ]
